#!/bin/sh
# This program is free software. It comes without any warranty, to
# the extent permitted by applicable law. You can redistribute it
# and/or modify it under the terms of the Do What The Fuck You Want
# To Public License, Version 2, as published by Sam Hocevar. See
# http://sam.zoy.org/wtfpl/COPYING for more details.

if test $# -le 0
then
	echo "Usage : netscape2json netscapeSourceFile" >&2
else
	# We need to make a well-formed XML file from the html one
	TMPFILE=/tmp/$1
	echo '<root>' > "$TMPFILE"
	sed 's,<\/\?\(DL\|DT\|p\)>,,g' $1 | sed 's,&,&amp;,g' \
		| grep '^<[Aa].*</[Aa]>' >> "$TMPFILE"
	echo '</root>' >> "$TMPFILE"
	# Real program parsing the file
	exec "./netscape2json.py" $TMPFILE
fi
